<div class="small-12 columns"><h1>AFP <small>Entidades</small></h1></div>
<hr>
<div class="small-12 columns">
    <form>
        <div class="row">
            <div class="small-12 columns">
                <fieldset>
                    <legend>Información de la AFP</legend>
                    <div class="row">
                        <div class="small-2 columns text-right">Nombre:</div>
                        <div class="small-10 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="small-2 columns text-right">Comisión Variable:</div>
                        <div class="small-4 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
                        <div class="small-2 columns text-right">Seguro:</div>
                        <div class="small-4 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="small-12 columns"><input type="button" class="button small radius" value="Guardar"></div>
                    </div>
                </fieldset>
            </div>
        </div>
    </form>
</div>
<div class="small-12 columns">
    <table width="100%">
        <thead>
            <tr>
                <th class="text-center" style="width: 5%;">Nro.</th>
                <th class="text-center" style="width: 75%;">AFP</th>
                <th class="text-center" style="width: 10%;">Com. Variable</th>
                <th class="text-center" style="width: 10%;">Seguro</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-right">1</td>
                <td>Integra</td>
                <td class="text-right">2.50%</td>
                <td class="text-right">1.50%</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">2</td>
                <td>Profuturo</td>
                <td class="text-right">2.50%</td>
                <td class="text-right">1.50%</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">3</td>
                <td>Habitat</td>
                <td class="text-right">2.50%</td>
                <td class="text-right">1.50%</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">4</td>
                <td>Prima</td>
                <td class="text-right">2.50%</td>
                <td class="text-right">1.50%</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
        </tbody>
    </table>
</div>