<div class="small-12 medium-8 large-7 columns">
    <div class="row">
        <div class="small-12 columns">
            <h2><small>Creación de Clientes</small></h2>
            <div class="row">
                <div class="small-12 columns">
                    <div class="panel" style="background-color: #FFF;">
                        <form method="post" action="<?php echo $this->url('create-client'); ?>">
                            <fieldset>
                                <legend>Cliente</legend>
                                <label>
                                    Nombre del Cliente
                                    <input type="text" placeholder="Ingrese el nombre del cliente" name="client-name" id="client-name">
                                </label>
                            </fieldset>
                            <fieldset>
                                <legend>Usuario</legend>
                                <label>
                                    Correo Electrónico
                                    <input type="text" placeholder="Ingrese el correo electrónico del usuario del cliente" name="user-email" id="user-email">
                                </label>
                            </fieldset>
                            <button class="button tiny radius">Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="small-12 medium-4 large-5 columns">
    &nbsp;
</div>
