<div class="small-12 medium-8 large-7 columns">
    <div class="row">
        <div class="small-12 columns">
            <h2><small>Listado de Clientes</small></h2>
            <div class="row">
                <div class="small-12 columns">
                    <a href="<?php echo $this->url('create-client'); ?>" class="button tiny radius">Crear Cliente</a>
                    <div class="panel">
                    <?php foreach($this->clients as $client) { ?>
                    <div class="row list files <?php echo $this->cycle(array('row-1', 'row-2'))->next() ?>">
                        <div class="small-12 columns"><a href="<?php echo $this->url('view-client', array('id'=>$client['clii_id'])); ?>"><?php echo $client['cliv_name']; ?></a></div>
                        <div class="small-8 large-8 columns text-small">Email: <?php echo $client['cluv_email']; ?></div>
                        <div class="small-4 large-4 columns text-small">Creado: <?php echo $client['clid_creation']->format('d-m-Y'); ?></div>
                    </div>
                    <?php } ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="small-12 medium-4 large-5 columns">
   &nbsp;
</div>
