<div class="small-12 medium-8 large-7 columns">
    <div class="row">
        <div class="small-12 columns">
            <h2><small>Edición de Clientes</small></h2>
            <div class="row">
                <div class="small-12 columns">
                    <div class="panel" style="background-color: #FFF;">
                        <form method="post" action="<?php echo $this->url('edit-client'); ?>" data-abide>
                            <input type="hidden" name="client-id" value="<?php echo $this->client['clii_id']; ?>">
                            <input type="hidden" name="user-id" value="<?php echo $this->user['clui_id']; ?>">
                            <fieldset>
                                <legend>Cliente</legend>
                                <label>
                                    Nombre del Cliente
                                    <input type="text" placeholder="Ingrese el nombre del cliente" name="client-name" id="client-name" value="<?php echo $this->client['cliv_name']; ?>">
                                </label>
                            </fieldset>
                            <fieldset>
                                <legend>Usuario</legend>
                                <label>
                                    Correo Electrónico
                                    <input type="text" placeholder="Ingrese el correo electrónico del usuario del cliente" name="user-email" id="user-email" value="<?php echo $this->user['cluv_email']; ?>">
                                </label>
                                <label>
                                    Password
                                    <small>obligatorio</small>
                                    <input type="password" placeholder="Ingrese el password del cliente" name="user-password" id="user-password" required pattern="[a-zA-Z0-9]+">
                                    <small class="error">Revise el password que ingresó</small
                                </label>
                            </fieldset>
                            <button class="button tiny radius">Guardar</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="small-12 medium-4 large-5 columns">
    &nbsp;
</div>
