<div class="small-12 columns">
    <div class="small-12 columns">
        <div class="small-1 columns text-right">Código</div>
        <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
        <div class="small-1 columns text-right">RUC</div>
        <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
        <div class="small-1 columns text-right">F. Inicio</div>
        <div class="small-3 columns"><div data-dojo-type="dijit/form/DateTextBox"></div></div>
    </div>
    <div class="small-12 columns">
        <div class="small-1 columns text-right">Estado</div>
        <div class="small-11 columns">
            <select data-dojo-type="dijit/form/FilteringSelect">
                <option>Seleccione Uno</option>
                <option>Activo</option>
                <option>Por Recuperar</option>
                <option>Inactivos</option>
                <option>Particulares Activos</option>
                <option>Cerrados / No Existen</option>
                <option>Particulares Inactivos</option>
            </select>
        </div>
    </div>
    <div class="small-12 columns">
        <div class="small-1 columns text-right">Nombre</div>
        <div class="small-8 columns end"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
    </div>
    <div class="small-12 columns">
        <div class="small-1 columns text-right">R.Social</div>
        <div class="small-8 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        <div class="small-3 columns"><input type="button" class="button tiny radius" value="Clientes por Supervisor"></div>
    </div>
    <div class="small-12 columns">
        <div class="small-1 columns text-right">Distrito</div>
        <div class="small-7 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        <div class="small-1 columns text-right">Dirección</div>
        <div class="small-3 columns">
            <select data-dojo-type="dijit/form/FilteringSelect">
                <option>Seleccione Uno</option>
                <option>Ancón</option>
                <option>Ate</option>
                <option>Barranco</option>
                <option>Bellavista</option>
                <option>Breña</option>
                <option>Callao</option>
            </select>
        </div>
    </div>
    <div class="small-12 columns">
        <div class="small-1 columns text-right">Contacto</div>
        <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        <div class="small-1 columns text-right">Gerente</div>
        <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        <div class="small-1 columns text-right">Email</div>
        <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
    </div>
    <div class="small-12 columns">
        <div class="small-1 columns text-right">Areas</div>
        <div class="small-8 columns"><textarea style="width: 100%; height: 40px;"></textarea></div>
        <div class="small-2 columns text-right">Dias Vence Facturación</div>
        <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
    </div>
    <div class="small-12 columns">
        <div class="small-1 columns text-right">Ubicacion</div>
        <div class="small-5 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        <div class="small-1 columns text-right">Cronog.</div>
        <div class="small-5 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
    </div>
    <div class="small-12 columns">
        <div class="small-1 columns text-right">Telf. 1</div>
        <div class="small-2 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        <div class="small-1 columns text-right">Telf. 2</div>
        <div class="small-2 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        <div class="small-1 columns text-right">Fax</div>
        <div class="small-2 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        <div class="small-1 columns text-right">Supervisor</div>
        <div class="small-2 columns">
            <select data-dojo-type="dijit/form/FilteringSelect" style="width: 100%;">
                <option>Seleccione Uno</option>
                <option>Armando García</option>
                <option>Luis Asto</option>
                <option>Cesar de la Cruz</option>>
            </select>
        </div>
    </div>
    <div class="small-12 columns">
        <div class="small-1 columns text-right">Precio</div>
        <div class="small-2 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        <div class="small-1 columns text-right">Moneda</div>
        <div class="small-2 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        <div class="small-1 columns text-right">Vendedor</div>
        <div class="small-2 columns end">
            <select data-dojo-type="dijit/form/FilteringSelect" style="width: 100%;">
                <option>Seleccione Uno</option>
                <option>Armando García</option>
                <option>Luis Asto</option>
                <option>Cesar de la Cruz</option>>
            </select>
        </div>
    </div>
    <div class="small-12 columns">
        <fieldset>
            <legend>Otros Datos</legend>
            <div class="small-12 columns">
                <div class="small-1 columns text-right">Notas</div>
                <div class="small-3 columns"><textarea style="width: 100%; height: 40px;"></textarea></div>
                <div class="small-2 columns text-right">Condiciones del Servicio</div>
                <div class="small-3 columns"><textarea style="width: 100%; height: 40px;"></textarea></div>
                <div class="small-2 columns end"><input type="button"
                                                        class="button tiny radius" value="Act. Zonas"></div>
            </div>
            <div class="small-12 columns">
                <div class="small-1 columns text-right">Giro en Certificado</div>
                <div class="small-2 columns">
                    <select data-dojo-type="dijit/form/FilteringSelect" style="width: 100%;">
                        <option>Seleccione Uno</option>
                    </select>
                </div>
                <div class="small-1 columns text-right">Giro Gral</div>
                <div class="small-2 columns">
                    <select data-dojo-type="dijit/form/FilteringSelect" style="width: 100%;">
                        <option>Seleccione Uno</option>
                    </select>
                </div>
                <div class="small-1 columns text-right">CIU</div>
                <div class="small-2 columns">
                    <select data-dojo-type="dijit/form/FilteringSelect" style="width: 100%;">
                        <option>Seleccione Uno</option>
                    </select>
                </div>
                <div class="small-1 columns text-right">Zona</div>
                <div class="small-2 columns">
                    <select data-dojo-type="dijit/form/FilteringSelect" style="width: 100%;">
                        <option>Seleccione Uno</option>
                    </select>
                </div>
            </div>
            <div class="small-12 columns">
                <div class="small-2 columns text-right">Periodicidad Desinsectación</div>
                <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
                <div class="small-1 columns text-right">1º Fum.</div>
                <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                                  style="width: 100%;"></div></div>
                <div class="small-1 columns text-right">Ult. Fum.</div>
                <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                                  style="width: 100%;"></div></div>
                <div class="small-1 columns text-right">Prox. Fum.</div>
                <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                                  style="width: 100%;"></div></div>
            </div>
            <div class="small-12 columns">
                <div class="small-2 columns text-right">Periodicidad Desratizado</div>
                <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
                <div class="small-2 columns text-right">Ult. Desratización</div>
                <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                                  style="width: 100%;"></div></div>
                <div class="small-2 columns text-right">Prox. Desratización</div>
                <div class="small-2 columns end"><div data-dojo-type="dijit/form/DateTextBox"
                                                      style="width: 100%;"></div></div>
            </div>
            <div class="small-12 columns">
                <div class="small-3 columns"><input type="checkbox"> Pendiende de Fumigación</div>
                <div class="small-3 columns"><input type="button"
                                                    class="button tiny radius" value="Imprimir Contrato"></div>
                <div class="small-1 columns text-right">Vence Certificado</div>
                <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                                  style="width: 100%;"></div></div>
                <div class="small-1 columns text-right">Recibe Certificado</div>
                <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                                  style="width: 100%;"></div></div>
            </div>
            <div class="small-12 columns">
                <div class="small-2 columns"><input type="checkbox"> Factura</div>
                <div class="small-2 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
                <div class="small-1 columns text-right">Emite</div>
                <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                                  style="width: 100%;"></div></div>
                <div class="small-1 columns text-right">Recibe</div>
                <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                                  style="width: 100%;"></div></div>
                <div class="small-2 columns"><input type="button" class="button tiny radius"
                                                    value="Imprimir Ordenes de Trabajo"></div>
            </div>
        </fieldset>
        <fieldset>
            <legend>Servicios Ofrecidos</legend>
            <div class="small-12 columns">
                <div class="small-3 columns text-right">Servicio de Desinsectación</div>
                <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
                <div class="small-3 columns text-right">Inspecciones</div>
                <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
                <div class="small-3 columns text-right">Desratizaciones</div>
                <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
            </div>
            <div class="small-12 columns">
                <div class="small-3 columns text-right">Limpieza de tanques</div>
                <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
                <div class="small-3 columns text-right">Desinfecciones</div>
                <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
                <div class="small-4 columns text-right"><input type="checkbox"> Incluído en el servicio</div>
            </div>
        </fieldset>
    </div>
    <div class="small-2 small-offset-10 columns">
        <input type="button" class="button small radius" value="Guardar">
    </div>
</div>