<div class="small-12 columns">
    <div class="small-3 columns text-right">Fecha de Coordinación:</div>
    <div class="small-3 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Persona de Coordinación:</div>
    <div class="small-6 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Observación de Coordinación:</div>
    <div class="small-6 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Fecha de Confirmación:</div>
    <div class="small-3 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Persona de Confirmación:</div>
    <div class="small-6 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Observación de Confirmación:</div>
    <div class="small-6 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Historial:</div>
    <div class="small-6 columns end"><textarea style="width: 100%; height: 200px;"></textarea></div>
</div>