<div class="small-12 columns">
    <table width="100%">
        <thead>
            <tr>
                <th class="text-center" style="width: 5%;">Nro.</th>
                <th class="text-center" style="width: 5%;">Código</th>
                <th class="text-center" style="width: 30%;">Nombre</th>
                <th class="text-center" style="width: 5%;">RUC</th>
                <th class="text-center" style="width: 35%;">Razón Social</th>
                <th class="text-center" style="width: 10%;">Teléfono</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-right">1</td>
                <td class="text-right">0001</td>
                <td>CLIENTE 0002</td>
                <td>20456650202</td>
                <td>CLIENTE 00002</td>
                <td>251-2815</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">2</td>
                <td class="text-right">0003</td>
                <td>CLIENTE 0004</td>
                <td>20100035392</td>
                <td>CLIENTE 00004</td>
                <td>&nbsp;</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">3</td>
                <td class="text-right">0050</td>
                <td>CLIENTE 00051</td>
                <td>20302690121</td>
                <td>CLIENTE 00002</td>
                <td>222-3188</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
        </tbody>
    </table>
</div>