<div class="small-12 columns"><h1>Clientes <small>Operaciones</small></h1></div>
<hr>
<div data-dojo-type="dijit/layout/TabContainer" style="width: 100%; height: 100%;" tabStrip="true">
	<div data-dojo-type="dijit/layout/ContentPane" title="Vista General"
	     href="<?php echo $this->url('cliente-general'); ?>">
	</div>
	<div data-dojo-type="dijit/layout/ContentPane" title="Actualizar"
	     href="<?php echo $this->url('cliente-actualizar'); ?>">
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Locales"
         href="<?php echo $this->url('cliente-locales'); ?>" selected="true">
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Servicios">
        Lorem ipsum and all around - last...
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Programación">
        Lorem ipsum and all around - last...
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Personal">
        Lorem ipsum and all around - last...
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Periodos">
        Lorem ipsum and all around - last...
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Pozos/Tanques">
        Lorem ipsum and all around - last...
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Planos">
        Lorem ipsum and all around - last...
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Coordinación">
        Lorem ipsum and all around - last...
    </div>
</div>