<div class="small-12 columns"><h1>Clientes <small>Operaciones</small></h1></div>
<hr>
<div data-dojo-type="dijit/layout/TabContainer" style="width: 100%; height: 100%;" tabStrip="true">
	<div data-dojo-type="dijit/layout/ContentPane" title="Vista General"
	     href="<?php echo $this->url('cliente-general'); ?>">
	</div>
	<div data-dojo-type="dijit/layout/ContentPane" title="Actualizar"
	     href="<?php echo $this->url('cliente-actualizar'); ?>">
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Locales"
         href="<?php echo $this->url('cliente-locales'); ?>">
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Servicios"
         href="<?php echo $this->url('cliente-servicios'); ?>">
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Programación"
         href="<?php echo $this->url('cliente-programacion'); ?>">
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Personal"
         href="<?php echo $this->url('cliente-personal'); ?>">
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Periodos"
         href="<?php echo $this->url('cliente-periodos'); ?>">
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Pozos/Tanques"
         href="<?php echo $this->url('cliente-pozo'); ?>">
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Planos"
         href="<?php echo $this->url('cliente-planos'); ?>">
    </div>
    <div data-dojo-type="dijit/layout/ContentPane" title="Coordinaciones" selected="true"
         href="<?php echo $this->url('cliente-coordinaciones'); ?>">
    </div>
</div>