<div class="small-12 columns">
    <div data-dojo-type="dijit/layout/TabContainer" style="width: 100%; height: 300px" tabStrip="true">
    	<div data-dojo-type="dijit/layout/ContentPane" title="Nuevo/Modificar"
    	     href="<?php echo $this->url('cliente-locales-nuevo'); ?>">
    	</div>
    	<div data-dojo-type="dijit/layout/ContentPane" title="Coordinaciones"
    	     href="<?php echo $this->url('cliente-locales-coordinacion'); ?>">
        </div>
    </div>
</div>
<hr>
<div class="small-12 columns">
    <table width="100%">
        <thead>
            <tr>
                <th class="text-center" style="width: 5%;">Nro.</th>
                <th class="text-center" style="width: 5%;">Edo.</th>
                <th class="text-center" style="width: 5%;">Código</th>
                <th class="text-center" style="width: 10%;">Nombre</th>
                <th class="text-center" style="width: 10%;">Dirección</th>
                <th class="text-center" style="width: 5%;">Contacto</th>
                <th class="text-center" style="width: 5%;">Cumpleaños</th>
                <th class="text-center" style="width: 5%;">Ult. Fum.</th>
                <th class="text-center" style="width: 5%;">Prox. Fum.</th>
                <th class="text-center" style="width: 5%;">Prox. Rat.</th>
                <th class="text-center" style="width: 5%;">Ult. Rat.</th>
                <th class="text-center" style="width: 5%;">Periodo</th>
                <th class="text-center" style="width: 5%;">Precio</th>
                <th class="text-center" style="width: 5%;">Moneda</th>
                <th class="text-center" style="width: 5%;">1º Fum.</th>
                <th class="text-center" style="width: 10%;">V. Cert.</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-right">1</td>
                <td class="text-right">&nbsp;</td>
                <td>0002</td>
                <td>CLIENTE 0002</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-12"></a></td>
            </tr>
        </tbody>
    </table>
</div>