<div class="small-12 columns">
    <div class="small-3 columns text-right">Dirección del Local:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
    <div class="small-3 columns text-right">Distrito:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Zona:</div>
    <div class="small-3 columns end"><div data-dojo-type="dijit/form/TextBox"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Contacto:</div>
    <div class="small-3 columns end"><div data-dojo-type="dijit/form/TextBox"></div></div>
    <div class="small-3 columns text-right">Teléfono:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Area Construída:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>

    <div class="small-3 columns text-right">Supervisor:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
</div>
<div class="small-12 columns">
    <fieldset>
        <div class="small-12 columns">
            <div class="small-2 columns text-right">Periodo Desinsectación</div>
            <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
            <div class="small-1 columns text-right">1º Fum.</div>
            <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                              style="width: 100%;"></div></div>
            <div class="small-1 columns text-right">Ult. Fum.</div>
            <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                              style="width: 100%;"></div></div>
            <div class="small-1 columns text-right">Prox. Fum.</div>
            <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                              style="width: 100%;"></div></div>
        </div>
        <div class="small-12 columns">
            <div class="small-2 columns text-right">Periodo Desratizado</div>
            <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
            <div class="small-2 columns text-right">Ult. Desratización</div>
            <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                              style="width: 100%;"></div></div>
            <div class="small-2 columns text-right">Prox. Desratización</div>
            <div class="small-2 columns end"><div data-dojo-type="dijit/form/DateTextBox"
                                                  style="width: 100%;"></div></div>
        </div>
        <div class="small-12 columns">
            <div class="small-2 columns text-right">Periodo Pozo</div>
            <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
            <div class="small-2 columns text-right">Ult. Tanque</div>
            <div class="small-2 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                              style="width: 100%;"></div></div>
            <div class="small-2 columns text-right">Prox. Tanque</div>
            <div class="small-2 columns end"><div data-dojo-type="dijit/form/DateTextBox"
                                                  style="width: 100%;"></div></div>
        </div>
    </fieldset>
</div>
<div class="small-12 columns">
    <fieldset>
        <legend>Servicios Ofrecidos</legend>
        <div class="small-12 columns">
            <div class="small-3 columns text-right">Servicio de Desinsectación</div>
            <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
            <div class="small-3 columns text-right">Inspecciones</div>
            <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
            <div class="small-3 columns text-right">Desratizaciones</div>
            <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
        </div>
        <div class="small-12 columns">
            <div class="small-3 columns text-right">Limpieza de tanques</div>
            <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
            <div class="small-3 columns text-right">Desinfecciones</div>
            <div class="small-1 columns"><div data-dojo-type="dijit/form/TextBox" style="width: 100%;"></div></div>
            <div class="small-4 columns text-right"><input type="checkbox"> Incluído en el servicio</div>
        </div>
    </fieldset>
</div>
<div class="small-2 small-offset-10 columns">
    <input type="button" class="button small radius" value="Guardar">
</div>