<div class="small-12 columns">
    <div class="small-3 columns text-right">Fecha de Coordinación:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/DateTextBox"></div></div>
    <div class="small-3 columns text-right">Persona de Coordinación:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Observación de Coordinación:</div>
    <div class="small-3 columns end"><div data-dojo-type="dijit/form/TextBox"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Fecha de Confirmación:</div>
    <div class="small-3 columns end"><div data-dojo-type="dijit/form/TextBox"></div></div>
    <div class="small-3 columns text-right">Persona de Confirmación:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Observación de Confirmación:</div>
    <div class="small-3 columns end"><div data-dojo-type="dijit/form/TextBox"></div></div>
</div>
<div class="small-12 columns">
    <div class="small-3 columns text-right">Historial:</div>
    <div class="small-9 columns"><textarea style="width: 100%; height: 40px;"></textarea></div>
</div>
<div class="small-2 small-offset-10 columns">
    <input type="button" class="button small radius" value="Guardar">
</div>