<div class="small-12 columns"><h1>Clientes <small>Operaciones</small></h1></div>
<hr>
<fieldset>
    <legend>Agregar Periodo</legend>
    <div class="small-12 columns">
        <div class="small-2 columns text-right">Correlativo:</div>
        <div class="small-1 end columns">
            <input type="textfield" data-dojo-type="dijit/form/TextBox" style="width: 100%">
        </div>
    </div>
    <div class="small-12 columns">
        <div class="small-2 columns text-right">Desde:</div>
        <div class="small-3 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
    </div>
    <div class="small-12 columns">
        <div class="small-2 columns text-right">Hasta:</div>
        <div class="small-3 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
    </div>
    <div class="small-12 columns">
        <div class="small-2 columns text-right">Local:</div>
        <div class="small-3 columns end">
            <select data-dojo-type="dijit/form/FilteringSelect">
                <option>Seleccione Uno</option>
                <option>Local 1</option>
                <option>Local 2</option>
                <option>Local 3</option>
                <option>Local 4</option>
            </select>
        </div>
    </div>
    <div class="small-12 columns">
        <div class="small-2 columns text-right">Historial:</div>
        <div class="small-10 columns"><textarea style="width: 100%; height: 40px;"></textarea></div>
    </div>
    <div class="small-2 small-offset-10 columns">
        <input type="button" class="button small radius" value="Guardar">
    </div>
</fieldset>