<div class="small-12 columns">
    <div class="small-3 columns end">
        <a href="#" onClick="changeScreenTo('<?php echo $this->url('cliente-personal-editar'); ?>'); return false;">
            <span class="fi-torsos-all size-24"></span> Agregar Nuevo
        </a>
    </div>
</div>
<hr>
<div class="small-12 columns">
    <table width="100%">
        <thead>
            <tr>
                <th class="text-center" style="width: 5%;">Nro.</th>
                <th class="text-center">Nombre.</th>
                <th class="text-center">Inicio</th>
                <th class="text-center">Cargo</th>
                <th class="text-center">Email</th>
                <th style="width: 5%;">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php for ($i = 0; $i < 10; $i++) { ?>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>