<fieldset>
    <legend>Pozo Séptico</legend>
    <div class="small-12 columns">
        <div class="small-2 columns text-right">Periodo:</div>
        <div class="small-3 columns"><input type="textfield" data-dojo-type="dijit/form/TextBox" style="width: 100%"></div>
        <div class="small-2 columns text-right">Fecha:</div>
        <div class="small-3 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
    </div>
</fieldset>
<fieldset>
    <legend>Tanques / Cisterna</legend>
        <div class="small-2 columns text-right">Periodo:</div>
        <div class="small-2 columns"><input type="textfield" data-dojo-type="dijit/form/TextBox" style="width: 100%"></div>
        <div class="small-2 columns text-right">Ultimo Servicio:</div>
        <div class="small-2 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
        <div class="small-2 columns text-right">Proximo Servicio:</div>
        <div class="small-2 columns end"><div data-dojo-type="dijit/form/DateTextBox" style="width: 100%;"></div></div>
</fieldset>