<div class="small-12 columns">
    <div class="small-1 columns text-right">Desde:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                              style="width: 100%;"></div></div>
    <div class="small-1 columns text-right">Hasta:</div>
    <div class="small-3 columns end"><div data-dojo-type="dijit/form/DateTextBox"
                                              style="width: 100%;"></div></div>
</div>
<div class="small-12 columns">
    <table width="100%">
        <thead>
            <tr>
                <th class="text-center" style="width: 5%;">Nro.</th>
                <th class="text-center">Cliente.</th>
                <th class="text-center">Prim.Fum.</th>
                <th class="text-center">Ult.Ser.</th>
                <th class="text-center">Prox.Ser.</th>
                <th class="text-center">Fech.Ini.</th>
                <th class="text-center">Vence Cert.</th>
                <th style="width: 5%;">&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <?php for ($i = 0; $i < 13; $i++) { ?>
            <tr>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
                <td>&nbsp;</td>
            </tr>
            <?php } ?>
        </tbody>
    </table>
</div>