<div class="small-12 columns">
    <div class="small-1 columns text-right">Desde:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                              style="width: 100%;"></div></div>
    <div class="small-1 columns text-right">Hasta:</div>
    <div class="small-3 columns"><div data-dojo-type="dijit/form/DateTextBox"
                                              style="width: 100%;"></div></div>
    <div class="small-1 columns text-right">Local:</div>
    <div class="small-3 columns">
        <select data-dojo-type="dijit/form/FilteringSelect">
            <option>Seleccione Uno</option>
            <option>Local 1</option>
            <option>Local 2</option>
            <option>Local 3</option>
            <option>Local 4</option>
        </select>
    </div>
</div>
<div class="small-12 columns">
    <fieldset>
        <legend>Ordenes de Trabajo</legend>
        <table width="100%">
            <thead>
                <tr>
                    <th class="text-center" style="width: 5%;">Nro.</th>
                    <th class="text-center">Edo.</th>
                    <th class="text-center">Número</th>
                    <th class="text-center">Fecha</th>
                    <th class="text-center">Ord.Madre</th>
                    <th class="text-center">Local</th>
                    <th class="text-center">Edo.</th>
                    <th class="text-center">Certi.</th>
                    <th class="text-center">Emite Certi.</th>
                    <th class="text-center">Rec.Certi.</th>
                    <th class="text-center">Expira Certi.</th>
                    <th class="text-center">Supervisor</th>
                    <th class="text-center">Garantía</th>
                    <th style="width: 5%;">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php for ($i = 0; $i < 4; $i++) { ?>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </fieldset>
</div>
<div class="small-12 columns">
    <fieldset>
        <legend>Certificados</legend>
        <table width="100%">
            <thead>
                <tr>
                    <th class="text-center" style="width: 5%;">Nro.</th>
                    <th class="text-center">Nº Certi</th>
                    <th class="text-center">Emisión</th>
                    <th class="text-center">Local</th>
                    <th class="text-center">Edo</th>
                    <th class="text-center">Rec.Certi.</th>
                    <th class="text-center">Expira Certi.</th>
                    <th class="text-center">Factura</th>
                    <th style="width: 5%;">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php for ($i = 0; $i < 4; $i++) { ?>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </fieldset>
</div>
<div class="small-12 columns">
    <fieldset>
        <legend>Facturas</legend>
        <table width="100%">
            <thead>
                <tr>
                    <th class="text-center" style="width: 5%;">Nro.</th>
                    <th class="text-center">Nº Docum</th>
                    <th class="text-center">Emisión</th>
                    <th class="text-center">Local</th>
                    <th class="text-center">Edo</th>
                    <th class="text-center">Moneda</th>
                    <th class="text-center">Total</th>
                    <th class="text-center">Fch.Pago</th>
                    <th style="width: 5%;">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php for ($i = 0; $i < 4; $i++) { ?>
                <tr>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                    <td>&nbsp;</td>
                </tr>
                <?php } ?>
            </tbody>
        </table>
    </fieldset>
</div>