<div class="small-12 columns"><h1>Usuarios y Accesos al Sistema</h1></div>
<hr>
<div class="small-12 columns">
    <table width="100%">
        <thead>
            <tr>
                <th class="text-center">Nro.</th>
                <th class="text-center">Usuario</th>
                <th class="text-center">Nombre</th>
                <th class="text-center">Apellido</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>1</td>
                <td>administra</td>
                <td>Diana</td>
                <td>&nbsp;</td>
                <td class="text-center"><a href="#"
                       onClick="changeScreenTo('<?php echo $this->url('user-edit', array('id' => 1)); ?>'); return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td>2</td>
                <td>almacen</td>
                <td>Almacen</td>
                <td>&nbsp;</td>
                <td class="text-center"><a href="#"
                       onClick="changeScreenTo('<?php echo $this->url('user-edit', array('id' => 2)); ?>'); return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td>3</td>
                <td>amauricio</td>
                <td>Mauricio Alejandro</td>
                <td>&nbsp;</td>
                <td class="text-center"><a href="#"
                       onClick="changeScreenTo('<?php echo $this->url('user-edit', array('id' => 3)); ?>'); return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td>4</td>
                <td>angelaq</td>
                <td>Angela</td>
                <td>Quiñones</td>
                <td class="text-center"><a href="#"
                       onClick="changeScreenTo('<?php echo $this->url('user-edit', array('id' => 4)); ?>'); return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td>5</td>
                <td>aperea</td>
                <td>Abel</td>
                <td>Perea</td>
                <td class="text-center"><a href="#"
                       onClick="changeScreenTo('<?php echo $this->url('user-edit', array('id' => 5)); ?>'); return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td>6</td>
                <td>benjamin</td>
                <td>Benjamin</td>
                <td>Castañeda</td>
                <td class="text-center"><a href="#"
                       onClick="changeScreenTo('<?php echo $this->url('user-edit', array('id' => 6)); ?>'); return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td>7</td>
                <td>cjulca</td>
                <td>Carlos</td>
                <td>Julca</td>
                <td class="text-center"><a href="#"
                       onClick="changeScreenTo('<?php echo $this->url('user-edit', array('id' => 7)); ?>'); return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td>8</td>
                <td>ecavero</td>
                <td>Edward</td>
                <td>Cavero Romaní</td>
                <td class="text-center"><a href="#"
                       onClick="changeScreenTo('<?php echo $this->url('user-edit', array('id' => 8)); ?>'); return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td>9</td>
                <td>czevallos</td>
                <td>Cesar</td>
                <td>Zevallos</td>
                <td class="text-center"><a href="#"
                       onClick="changeScreenTo('<?php echo $this->url('user-edit', array('id' => 9)); ?>'); return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td>10</td>
                <td>emelgar</td>
                <td>Eloy</td>
                <td>Melgar Sulca</td>
                <td class="text-center"><a href="#"
                       onClick="changeScreenTo('<?php echo $this->url('user-edit', array('id' => 10)); ?>'); return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
        </tbody>
    </table>
</div>