<div class="small-12 columns"><h1>Artículos de Sistema <small>Entidades</small></h1></div>
<hr>
<div class="small-12 columns">
    <form>
        <div class="row">
            <div class="small-12 columns">
                <fieldset>
                    <legend>Datos Generales</legend>
                    <div class="row">
                        <div class="small-2 columns text-right">Código:</div>
                        <div class="small-3 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
                        <div class="small-2 columns text-right">Línea:</div>
                        <div class="small-3 columns">
                            <select data-dojo-type="dijit/form/FilteringSelect">
                                <option selected>Seleccione Uno</option>
                                <option>Movilidad de Fumigación</option>
                                <option>Movilidad para inspecciones</option>
                                <option>Pago del personal</option>
                                <option>Producto</option>
                                <option>Tubos - Material desratiza</option>
                            </select>
                        </div>
                    </div>
                </fieldset>
                <fieldset>
                    <legend>Unidad de Medida</legend>
                    <div class="row">
                        <div class="small-2 columns text-right">Unidad de compra:</div>
                        <div class="small-4 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
                        <div class="small-6 columns">
                            <label><input type="checkbox"> Plaza Vea</label>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="small-12 columns"><input type="button" class="button small radius" value="Guardar"></div>
                    </div>
                </fieldset>
            </div>
        </div>
    </form>
</div>
<div class="small-12 columns">
    <table width="100%">
        <thead>
            <tr>
                <th class="text-center" style="width: 5%;">Nro.</th>
                <th class="text-center" style="width: 10%;">Código</th>
                <th class="text-center" style="width: 85%;">Nombre</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-right">1</td>
                <td class="text-right">01</td>
                <td>Almacenes</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">2</td>
                <td class="text-right">02</td>
                <td>Area de Jabas</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">3</td>
                <td class="text-right">03</td>
                <td>Areas de Producción</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">4</td>
                <td class="text-right">04</td>
                <td>Area de Ventas</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">5</td>
                <td class="text-right">05</td>
                <td>Azotea</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">6</td>
                <td class="text-right">06</td>
                <td>Bar</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
        </tbody>
    </table>
</div>