<?php
/**
 * Configuration file generated by ZFTool
 * The previous configuration file is stored in application.config.old
 *
 * @see https://github.com/zendframework/ZFTool
 */
return array(
    'modules' => array(
        'Application',
        'DoctrineModule',
        'DoctrineORMModule',
        'Common',
        'Security',
        'Entity',
        'Operation'
    ),
    'module_listener_options' => array(
        'module_paths' => array(
            './module',
            './vendor',
            './library'
        ),
        'config_glob_paths' => array(
            'config/autoload/{{,*.}global,{,*.}local}.php',
            'module/{*}/config/autoload/{,*.}{global,local}.php'
        ),
        'cache_dir' => 'data/cache/'
    )
);
