<div class="small-12 columns"><h1>Almacenes de Artículos <small>Entidades</small></h1></div>
<hr>
<div class="small-12 columns">
    <form>
        <div class="row">
            <div class="small-12 columns">
                <fieldset>
                    <legend>Lugares de depósito de los Artículos</legend>
                    <div class="row">
                        <div class="small-2 columns text-right">Código:</div>
                        <div class="small-10 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="small-2 columns text-right">Nombre:</div>
                        <div class="small-4 columns"><div data-dojo-type="dijit/form/TextBox"></div></div>
                        <div class="small-2 columns text-right">Responsable:</div>
                        <div class="small-4 columns">
                            <select data-dojo-type="dijit/form/FilteringSelect">
                                <option selected>Seleccione Uno</option>
                                <option>Alan David Antitupa Davila</option>
                                <option>Alan Gabriel Dolores Tarazona</option>
                                <option>Alejandro Santiago Aspiros Delgado</option>
                                <option>Alexander Joel Milla Salinas</option>
                                <option>Alvaro Arbulu Cuadros</option>
                                <option>Angel Ccanccapa Tapara</option>
                            </select>
                        </div>
                    </div>
                    <br>
                    <div class="row">
                        <div class="small-12 columns"><input type="button" class="button small radius" value="Guardar"></div>
                    </div>
                </fieldset>
            </div>
        </div>
    </form>
</div>
<div class="small-12 columns">
    <table width="100%">
        <thead>
            <tr>
                <th class="text-center" style="width: 5%;">Nro.</th>
                <th class="text-center" style="width: 10%;">Código</th>
                <th class="text-center" style="width: 45%;">Nombre</th>
                <th class="text-center" style="width: 30%;">Responsable</th>
                <th>&nbsp;</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td class="text-right">1</td>
                <td class="text-right">01</td>
                <td>Almacen Principal</td>
                <td>Sin Asignar</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">2</td>
                <td class="text-right">02</td>
                <td>Arequipa</td>
                <td>Sin Asignar</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
            <tr>
                <td class="text-right">3</td>
                <td class="text-right">03</td>
                <td>Trujillo</td>
                <td>Sin Asignar</td>
                <td class="text-center"><a href="#"
                       onClick="return false;"
                       class="step fi-page-edit size-24"></a></td>
            </tr>
        </tbody>
    </table>
</div>