<form>
    <div class="row">
        <div class="large-12 columns">
            <label>Cliente
                <input type="text" />
            </label>
        </div>
    </div>
    <div class="row">
        <div class="large-4 columns">
            <label>Local
                <input type="text" />
            </label>
        </div>
        <div class="large-4 columns">
            <label>Servicios Realizados
                <input type="text" />
            </label>
        </div>
        <div class="large-2 columns">
            <label>Fecha
                <input type="text" />
            </label>
        </div>
        <div class="large-2 columns">
            <label>Hora
                <input type="text" />
            </label>
        </div>
    </div>
    <div class="row">
        <div class="large-4 columns">
            <label>Productos utilizados
                <textarea></textarea>
            </label>
        </div>
        <div class="large-4 columns">
            <label>Areas Tratadas
                <textarea></textarea>
            </label>
        </div>
        <div class="large-4 columns">
            <label>Problemas Encontrados
                <textarea></textarea>
            </label>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <label>Recomendaciones
                <textarea></textarea>
            </label>
        </div>
    </div>
    <div class="row">
        <div class="large-4 columns end">
            <label>Imagen
                <input type="file" />
            </label>
        </div>
    </div>
    <div class="row">
        <div class="large-12 columns">
            <a href="#" class="button radius small">Enviar</a>
        </div>
    </div>
</form>