<?php

namespace Application\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebsiteTbSectionContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteTbSectionContentRepository extends EntityRepository
{
}
