<?php

namespace Application\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WebsiteTbSectionTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsiteTbSectionTypeRepository extends EntityRepository
{
}
